name: Create Jira Issue

on:
  push:
    branches:
      - main 
      
jobs:
  create-jira-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Jira Issue
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: https://prodevans-saravanann.atlassian.net
        run: |
          ./jira.sh 
